version: '3'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: project_db
      POSTGRES_USER: project_user
      POSTGRES_PASSWORD: project_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    build: .
    command: uvicorn project.asgi:application --host 0.0.0.0 --port 8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DEBUG: '1'
      SECRET_KEY: your_secret_key
      DB_NAME: project_db
      DB_USER: project_user
      DB_PASSWORD: project_password
      DB_HOST: db

  celery:
    build: .
    command: celery -A project worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
      - db
    environment:
      DB_NAME: project_db
      DB_USER: project_user
      DB_PASSWORD: project_password
      DB_HOST: db

  celery-beat:
    build: .
    command: celery -A project beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
      - db
    environment:
      DB_NAME: project_db
      DB_USER: project_user
      DB_PASSWORD: project_password
      DB_HOST: db

volumes:
  postgres_data:
