# Generated by Django 5.1.1 on 2024-09-14 14:23

import location_field.models.plain
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63, null=True),
        ),
    ]
