# Generated by Django 5.1.1 on 2024-09-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_library_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='borrowed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
